import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Plus, Search, Trash2, X } from 'lucide-react'
import { api } from '../lib/api'
import type { CareerRecord } from '../types'
import { Card, Empty, PageHeader, Spinner, Status } from '../components/UI'

const types=['project','internship','certification','workshop','achievement']
export function Repository(){const [records,setRecords]=useState<CareerRecord[]>();const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [modal,setModal]=useState(false);const load=()=>api<CareerRecord[]>('/records').then(setRecords);useEffect(()=>{void load()},[]);const visible=useMemo(()=>records?.filter(r=>(filter==='all'||r.record_type===filter)&&(`${r.title} ${r.description||''}`.toLowerCase().includes(search.toLowerCase()))),[records,filter,search]);async function remove(id:string){if(!confirm('Delete this career record? The original document, if any, is not deleted.'))return;await api(`/records/items/${id}`,{method:'DELETE'});load()}if(!records)return <Spinner/>;return <><PageHeader eyebrow="Source of truth" title="Career repository" description="Maintain projects, experience, credentials and achievements with clear evidence states." action={<button className="primary" onClick={()=>setModal(true)}><Plus/>Add record</button>}/><div className="toolbar"><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search titles and descriptions"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All categories</option>{types.map(t=><option key={t}>{t}</option>)}</select></div>{visible?.length?<div className="repository-grid">{visible.map(r=><Card key={r.id}><div className="card-head"><span className="record-type">{r.record_type}</span><button className="icon danger" onClick={()=>remove(r.id)}><Trash2 size={17}/></button></div><h2>{r.title}</h2><p>{r.organization||'Independent work'}</p><p className="clamp">{r.description||'No description added.'}</p><div className="chips">{r.skills.map(s=><span key={s}>{s}</span>)}</div><div className="record-foot"><Status value={r.evidence_state.replace('_',' ')}/><span>{r.start_date||new Date(r.created_at).toLocaleDateString()}</span></div></Card>)}</div>:<Empty title="No matching career records" description="Add one manually or confirm information extracted from a document." action={<button className="primary" onClick={()=>setModal(true)}>Add your first record</button>}/>} {modal&&<RecordModal close={()=>setModal(false)} saved={()=>{setModal(false);load()}}/>}</>}
function RecordModal({close,saved}:{close:()=>void;saved:()=>void}){const [type,setType]=useState('project');const [title,setTitle]=useState('');const [org,setOrg]=useState('');const [description,setDescription]=useState('');const [skills,setSkills]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);await api('/records',{method:'POST',body:JSON.stringify({record_type:type,title,organization:org||null,description:description||null,skills:skills.split(',').map(s=>s.trim()).filter(Boolean)})});saved()}return <div className="modal-backdrop"><div className="modal"><div className="card-head"><div><p className="eyebrow">Manual entry</p><h2>Add career record</h2></div><button className="icon" onClick={close}><X/></button></div><form onSubmit={submit} className="form-grid"><label>Category<select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Organization<input value={org} onChange={e=>setOrg(e.target.value)}/></label><label className="full">Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="full">Skills <small>Comma separated</small><input value={skills} onChange={e=>setSkills(e.target.value)} placeholder="Java, PostgreSQL, React"/></label><div className="modal-actions full"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></div></div>}
